### ISSUE TITLE
Debug error (Process 'command 'C:\Src\flutter\bin\flutter.bat'' finished with non-zero exit value 1)

### ISSUE THREAD

**Issue by Lunedor** [xieweizhi/tubi_tv_flutter#1]
I am getting below error,

<
Compiler message:
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/Src/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('/C:/Src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
        informationCollector: (StringBuffer information) {
                              ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 803

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1
>

**Comment by xieweizhi** [comment]
@Lunedor Thanks for the report. Updated the `CachedNetworkImage` in https://github.com/xieweizhi/tubi_tv_flutter/commit/9a4a0d9c917507f043464fdfcea98d5fda6e1f90. It should be working now.
